"""Add file_hash to Transcript

Revision ID: 35c88d91e71e
Revises: 581dc104a85c
Create Date: 2026-06-22 14:37:55.860647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35c88d91e71e'
down_revision: Union[str, Sequence[str], None] = '581dc104a85c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_transcripts_file_hash'), 'transcripts', ['file_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripts_file_hash'), table_name='transcripts')
    op.drop_column('transcripts', 'file_hash')
    # ### end Alembic commands ###
