"""Add celery_task_id and processing_summary to Transcript

Revision ID: 581dc104a85c
Revises: 671ce19ff326
Create Date: 2026-06-22 12:40:59.473870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '581dc104a85c'
down_revision: Union[str, Sequence[str], None] = '671ce19ff326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'locked_document_id')
    op.add_column('transcripts', sa.Column('celery_task_id', sa.String(length=255), nullable=True))
    op.add_column('transcripts', sa.Column('processing_summary', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'processing_summary')
    op.drop_column('transcripts', 'celery_task_id')
    op.add_column('chat_sessions', sa.Column('locked_document_id', sa.UUID(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
