"""add extracted_requirements to transcript

Stores the raw extraction output before comparison runs, so comparison can be re-run later
from stored data instead of re-extracting the transcript.

Written BY HAND, not autogenerated. This project's schema has drifted from its migrations —
`meeting_minutes` was created by create_all with no revision — so --autogenerate would try to
create tables that already exist.

Nullable on purpose: existing transcripts keep NULL, nothing reads the column yet, and the
downgrade is a clean drop.

Revision ID: a7c3e1b9d204
Revises: d1f499637722
Create Date: 2026-10-05

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a7c3e1b9d204'
down_revision: Union[str, Sequence[str], None] = 'd1f499637722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add the column. Nullable, so existing rows are untouched."""
    op.add_column(
        'transcripts',
        sa.Column('extracted_requirements', sa.JSON(), nullable=True),
    )


def downgrade() -> None:
    """Drop the column. Loses stored extractions — comparison would need re-extraction."""
    op.drop_column('transcripts', 'extracted_requirements')
