"""add comparison_status and comparison_version to transcript

Tracks comparison separately from ingestion so comparison can run detached from upload, and
records which matching algorithm produced a transcript's requirements.

Hand-written, not autogenerated: this project's schema has drifted from its migrations
(`meeting_minutes` came from create_all with no revision), so --autogenerate would try to
create tables that already exist.

IMPORTANT — existing rows are marked 'compared', not 'pending'. Transcripts already processed
DID go through comparison. Leaving them 'pending' would make the future background worker
re-compare them, duplicating their requirements and version rows.

Revision ID: b4f82a6c1e37
Revises: a7c3e1b9d204
Create Date: 2026-10-05

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b4f82a6c1e37'
down_revision: Union[str, Sequence[str], None] = 'a7c3e1b9d204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'transcripts',
        sa.Column('comparison_status', sa.String(length=50),
                  nullable=True, server_default='pending'),
    )
    op.add_column(
        'transcripts',
        sa.Column('comparison_version', sa.String(length=50), nullable=True),
    )

    # Anything already ingested was compared under the original algorithm. Marking it prevents
    # a later worker from processing it a second time.
    op.execute(
        "UPDATE transcripts "
        "SET comparison_status = 'compared', comparison_version = 'v1-gates' "
        "WHERE status = 'processed'"
    )


def downgrade() -> None:
    op.drop_column('transcripts', 'comparison_version')
    op.drop_column('transcripts', 'comparison_status')
