"""SERVER CHAIN: add extracted_requirements, comparison_status, comparison_version

READ THIS BEFORE COPYING ANYTHING TO A SERVER.

Local and production have different Alembic histories and have had since 2026-06-23:

    production :  ff33b853ad6c  ("create all tables", a single autogenerated snapshot)
    local      :  671ce19ff326 -> 581dc104a85c -> 35c88d91e71e -> d1f499637722
                                                      -> a7c3e1b9d204 -> b4f82a6c1e37

Neither chain contains the other's revisions, so `alembic upgrade head` on production does
nothing with the local files: their down_revision (d1f499637722) does not exist there.

This revision applies the SAME schema change as a7c3e1b9d204 + b4f82a6c1e37 combined, but
chains off the production revision so production can run it through Alembic normally.

DEPLOYMENT RULE
---------------
    production  : copy THIS file only.
    local       : already covered by a7c3e1b9d204 + b4f82a6c1e37 — do not run this.

Copying all three to one machine gives Alembic two unconnected roots, and every subsequent
`alembic upgrade head` fails with "Multiple head revisions are present".

Revision ID: c5d91f3a7b22
Revises: ff33b853ad6c
Create Date: 2026-10-06

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c5d91f3a7b22'
down_revision: Union[str, Sequence[str], None] = 'ff33b853ad6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Raw extraction output, saved before comparison runs, so comparison can be replayed
    # against a better algorithm without paying to extract the transcript again.
    op.add_column(
        'transcripts',
        sa.Column('extracted_requirements', sa.JSON(), nullable=True),
    )

    # Comparison tracked separately from `status`, which stays the ingestion state the admin
    # UI polls on. Overloading `status` would break that poll.
    op.add_column(
        'transcripts',
        sa.Column('comparison_status', sa.String(length=50),
                  nullable=True, server_default='pending'),
    )

    # Which matching algorithm produced this transcript's requirements, so a future rebuild
    # can be told apart from the run it replaced.
    op.add_column(
        'transcripts',
        sa.Column('comparison_version', sa.String(length=50), nullable=True),
    )

    # Anything already ingested DID go through comparison. Marking it stops a future runner
    # re-comparing it and duplicating its requirements and version rows.
    op.execute(
        "UPDATE transcripts "
        "SET comparison_status = 'compared', comparison_version = 'v1-gates' "
        "WHERE status = 'processed'"
    )


def downgrade() -> None:
    op.drop_column('transcripts', 'comparison_version')
    op.drop_column('transcripts', 'comparison_status')
    op.drop_column('transcripts', 'extracted_requirements')
